# Generated by Django 3.2.19 on 2025-04-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(limit_choices_to='Client', on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(limit_choices_to='Employer', on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
