# Generated by Django 3.2.19 on 2025-04-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250428_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
