# Generated by Django 3.2.19 on 2025-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20250428_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
