# Generated by Django 3.2.19 on 2025-04-28 08:01

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Room_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.room', validators=[base.models.validate_if_room_is_available]),
        ),
    ]
