# Generated by Django 3.2.19 on 2025-04-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20250428_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hotel'),
        ),
    ]
