# Generated by Django 3.2.19 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact',
            field=models.IntegerField(default=673044019),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='Date_left',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
