# Generated by Django 3.2.19 on 2025-04-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
