# Generated by Django 3.2.19 on 2025-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20250429_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='room',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='rank',
        ),
    ]
